services:
  question-cards:
    container_name: question-cards
    image: ghcr.io/jfriisj/question-cards:latest
    ports:
      - "86:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - cloudflare
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  cloudflare:
    external: true
