services:
  vennekredsen:
    container_name: question-cards
    restart: unless-stopped
    image: ghcr.io/jfriisj/question-cards:latest
    ports:
      - "86:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
