services:
  question-cards:
    container_name: question-cards
    image: ghcr.io/jfriisj/question-cards:latest
    ports:
      - "86:80" # Map port 80 in the container to port 86 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    restart: unless-stopped
#    networks:
#      - cloudflare
#
#networks:
#  cloudflare:
#    external: true
